os:
  - osx
language: swift
sudo: required
dist: trusty
osx_image: xcode9.1
script:
  - xcodebuild clean build -project SubSonicAPI.xcodeproj -scheme SubSonicAPI-Package -sdk macosx -quiet
  - xcodebuild clean test -project SubSonicAPI.xcodeproj -scheme SubSonicAPI-Package -sdk macosx -quiet
after_success:
  - bash <(curl -s https://codecov.io/bash)
