os:
  - osx
language: swift
sudo: required
dist: trusty
osx_image: xcode9.1
script:
  - xcodebuild clean test -scheme SubSonicAPI-Package CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
after_success:
  - bash <(curl -s https://codecov.io/bash)
