os: osx
language: swift
osx_image: xcode11.3
xcode_project: SubSonicAPI.xcodeproj
xcode_scheme: SubSonicAPI-Package
xcode_destination: platform=OS X,arch=x86_64
script: xcodebuild clean build test -project SubSonicAPI.xcodeproj -destination 'platform=OS X,arch=x86_64' -scheme SubSonicAPI-Package -sdk macosx -quiet
