# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "9.1"

    steps:
      - checkout


      # Build the app and run tests
      - run:
          name: Build and run tests
          command: xcodebuild clean build -project SubSonicAPI.xcodeproj -destination 'platform=OS X,arch=x86_64' -scheme SubSonicAPI-Package -sdk macosx -quiet
          command: xcodebuild clean test -project SubSonicAPI.xcodeproj -scheme SubSonicAPI-Package -destination 'platform=OS X,arch=x86_64' -sdk macosx -quiet
          environment:
            SCAN_DEVICE: iPhone 6
            SCAN_SCHEME: WebTests

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs

